language: node_js
node_js:
- '12'
- '10'
cache:
  yarn: true
  directories:
  - node_modules
before_script:
- yarn check-format
- yarn lint
script:
- yarn test --coverage
- yarn build
after_success: yarn codecov
deploy:
  provider: npm
  email: ruka.araujo@gmail.com
  api_key:
    secure: jvCrn5FfAtHTsgLv+9CPsuGKB/9VH7le2jFkzhmYBNi0AhTUIShpB3lVwB+eQ3/Gody9+sqJLeJBs52yM+8HP0hcpcjpYuCbRZlHqQSr+Bd6BuBpv5Wd+c0jh18odxSYA/R75UEwPkDUyLPDYjABSQX4SoJp2e7LVNq1LKA/TVeXQSQTJn0MvUHREaWHa1XkhMIoQ9F0/FIAyGXlJlS5CBXN0s5rkn1BaESpqHTOzy9SWKtXrO/VItDssVY7m54jd+Itu7eZrtfAY0OFPd3JuUw0nqNCG0uluE5s+UPA5oAVUEU/4FzrigEj1hfRFysrV5rSTfzaoPbM43vwsjjuNbyA1pJUZ2UpqPk53Yt0z0s/yl1rkAzTI27wo2mz3/Xa4gYkl9CQxCw8xvZpVJo4SyiJI6wS8Xy2RegQ3yP3i7LY6UanOaAHHrsb5J3HCc6AMF/TaRjjgVlaxhrnONf93Gvtma4dHG0AJDaVo9LdXUbyBOGJ2Sy/qR+CnJ8105nc2GuFXWYGRy6H6GqrQdPpecfEVhA9ZLEOqOA0zPXPrpRjURNdk5N19UDx9I+5HzxVtLKizTlfIoxmMQLqFRV0lpn2YUmqyYozdF6QGyPxxpmdLtPZAF7f0RD+O+6rgOtKu+9rpnPb+djj51+H0mWoUgdbwYSOxxPAjxTmqp0BpWo=
  on:
    tags: true
    repo: zalando-incubator/graphql-jit
