# for github.com
approvals:
  # needed to keep the compliance checks happy
  groups:
    zalando:
      minimum: 2
      from:
        orgs:
          - zalando

X-Zalando-Team: "pathfinder"
X-Zalando-Type: "code"
